### ISSUE TITLE
 No module named 'object_detection'

### ISSUE THREAD

**Issue by surajdurgesht** [ArifSohaib/AutonomousRobotChallenge#1]
i am getting error this,

  File "D:/Hackathon/AutonomousRobotChallenge/object_detection_cam.py", line 24, in <module>
    from object_detection.utils import ops as utils_ops

ModuleNotFoundError: No module named 'object_detection'

**Comment by ArifSohaib** [comment]
You need to run the code from the tensorflow research directory one level above the object detection directory.

**Comment by surajdurgesht** [comment]
Thanks, can i get connection circuit  whole diagram ?
Thanks,
-------------------
Suraj Durgesht
Department of Electronic and Commnunication Engineering,
IIIT Dharwad, Karnataka, India.

Click here to Reply, Reply to all, or Forward

**Comment by ArifSohaib** [comment]
https://halckemy.s3.amazonaws.com/uploads/attachments/636777/farmaidcircuit1_IU99juEAV2.png

**Comment by ArifSohaib** [comment]
closing it now
